services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file: .env
    environment:
      SELENIUM_REMOTE_URL: http://selenium:4444
    volumes:
      - ./:/app
    depends_on:
      - selenium
      - neo4j
    # command: uv run python -m src.scrape_psn
    command: uv run python -m src.scrape_psn


  selenium:
    image: selenium/standalone-chromium:latest
    shm_size: 2gb
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=120
    ports:
      - "4444:4444"   # WebDriver endpoint + Grid UI
      - "7900:7900"   # noVNC for manual control (password: secret)

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: "${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-neo4j}"
      NEO4j_server_memory_heap_initial__size: 512m
      NEO4j_server_memory_heap_max__size: 512m
      NEO4J_server_memory_pagecache_size: 256m
    ports:
      - "7474:7474"   # HTTP UI
      - "7687:7687"   # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
volumes:
  neo4j_data:
  neo4j_logs:


